spring:
  application:
    name: springsecurity

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql


